# docker compose up --build -d

services:
  webserver:
    build:
      context: .
    image: adianti_server:debian-11_php8.1
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - network
    volumes:
      - ./php-prod.ini:/etc/php/8.1/apache2/php.ini
      - ./html:/var/www/html
      - ./logs/apache2:/var/log/apache2
      - ./ssl-cert.crt:/etc/ssl/certs/ssl-cert-snakeoil.pem
      - ./ssl-cert.key:/etc/ssl/private/ssl-cert-snakeoil.key
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - mariadb
    extra_hosts:
      - host.docker.internal:host-gateway

  mariadb:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      #MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - network

  phpmyadmin:
    image: phpmyadmin 
    restart: always
    environment:
      PMA_ARBITRARY: 1
    ports:
      - 8080:80
    networks:
      - network

networks:
  network:
    driver: bridge
