# docker compose up --build -d

version: '3.8'
services:
  webserver:
    build:
      context: .
    image: adianti_server:debian-11_php8.1
    restart: on-failure
    ports:
      - "80:80"
    networks:
      - network
    volumes:
      - ./php-prod.ini:/etc/php/8.1/apache2/php.ini
      - ./html:/var/www/html
      - ./logs/apache2:/var/log/apache2
    depends_on:
      - mariadb
    extra_hosts:
      - host.docker.internal:host-gateway

  mariadb:
    image: mariadb:10.11
    restart: on-failure
    environment:
      #MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - network

  phpmyadmin:
    image: phpmyadmin 
    restart: always
    environment:
      PMA_ARBITRARY: 1
    ports:
      - 8080:80
    networks:
      - network

networks:
  network:
    driver: bridge
